### PR TITLE
Fix : Issue in readMe file link not working

### PR DESCRIPTION
**Pull request by Ankush1oo8**
## Description

**Kindly take a look at [CONTRIBUTING.md](https://github.com/scikit-hep/vector/blob/main/.github/CONTRIBUTING.md).**

_Please describe the purpose of this pull request. Reference and link to any relevant issues or pull requests._

## Checklist

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't any other open Pull Requests for the required change?
- [x] Does your submission pass pre-commit? (`$ pre-commit run --all-files` or `$ nox -s lint`)
- [x] Does your submission pass tests? (`$ pytest` or `$ nox -s tests`)
- [x] Does the documentation build with your changes? (`$ cd docs; make clean; make html` or `$ nox -s docs`)
- [x] Does your submission pass the doctests? (`$ pytest --doctest-plus src/vector/` or `$ nox -s doctests`)

## Before Merging
fixed issue #535
the link in readme file was not working

In README, the link to [coffea.nanoevents.methods.vector](https://coffeateam.github.io/coffea/modules/coffea.nanoevents.methods.vector.html) doesn't work. The current link in the github will be linked to 404 page.

updated to 

..., and [coffea.nanoevents.methods.vector](https://coffea-hep.readthedocs.io/en/latest/modules/coffea.nanoevents.methods.vector.html) (backed by Scikit-HEP/vector since v2024.8).

- [x] Summarize the commit messages into a brief review of the Pull request.

### CODE REVIEW

**Review by Saransh-cpp — APPROVED** [review]
Thanks, @Ankush1oo8!

**Comment by Saransh-cpp** [comment]
The tests are failing because of https://github.com/dask-contrib/dask-awkward/issues/557. I'll merge this given that this PR only changes the README.

**Review by Saransh-cpp — CHANGES_REQUESTED** [review]
On second thought, @Ankush1oo8 could you also update - https://github.com/scikit-hep/vector/blob/main/docs/index.rst?

**Comment by Saransh-cpp** [comment]
Could you also please create a PR from a non-`main` branch? Thanks!

**Comment by Ankush1oo8** [comment]
Okey I will update the other file and make a pr from other branch

**Pull request closed without merging**
