### PR TITLE
deltaRapidityPhi and deltaRapidityPhi2 + documentation and testing!

### PR DESCRIPTION
**Pull request by jpivarski**
This is a follow-up on #175, which actually documents the new functions.

### CODE REVIEW

**Comment by jpivarski** [comment]
@raymondEhlers, if you're done with this, I'll merge it. (It looks good to me!)

**Comment by jpivarski** [comment]
> ImportError: cannot import name 'environmentfilter' from 'jinja2' (/home/docs/checkouts/readthedocs.org/user_builds/vector/envs/186/lib/python3.8/site-packages/jinja2/__init__.py)

Ugh, this is some version issue in Sphinx. I saw it on some other repo; I'm checking to see how it was fixed elsewhere.

**Comment by raymondEhlers** [comment]
I'm all done, thanks!

**Comment by jpivarski** [comment]
See https://github.com/scikit-hep/vector/pull/175#issuecomment-1106602474.

**Pull request closed without merging**
