### PR TITLE
Implements deltaRapidityPhi and deltaRapidityPhi2.

### PR DESCRIPTION
**Pull request by jpivarski**
@raymondEhlers, please add tests!

### CODE REVIEW

**Comment by raymondEhlers** [comment]
I finally got around to adding these tests and updating the docs, but I can't seem to figure out how to push to this PR (I'm not sure if I have permissions?). In the meantime, I pushed my changes to the branch [`deltaRapidityPhi` on my fork](https://github.com/raymondEhlers/vector/tree/deltaRapidityPhi).

Please have a look when you have a chance and let me know if you'd like any changes!

**Comment by jpivarski** [comment]
You ought to be able to make a pull request (I don't think there are any limitations on who can make a pull request from an outside fork), but I can also do that from your repo, so I will.

Meanwhile, I'll merge this PR so that the PR from your repo can go directly to main. The changes you made that are the same as the changes in this branch _should_ just be recognized as the same thing and not duplicated, but we'll see when I make a PR from your repo to Vector:main.

**Comment by raymondEhlers** [comment]
I could make a separate PR - I just wasn't sure if you wanted to keep it all in one place (I know there are some ways to do so, but I've only done it from the maintainer side). Thanks for opening the separate PR!

**Comment by jpivarski** [comment]
I think the thing I need to do to fix the Sphinx error is to merge with upstream main. If you can do that in a new PR, I think that would work. I'll close #186 in anticipation of that.

**Pull request merged**
