### PR TITLE
Implement all math

### PR DESCRIPTION
**Pull request by jpivarski**
Just writing functions in the `compute` directory for now, with no synonyms. Test against the `ROOT::Math::*` equivalents.

## Implement on Planar, to be inherited by Spatial and Lorentz

   - [x] `x`
   - [x] `y`
   - [x] `rho` (`perp`, `pt`)
   - [x] `rho2` (`perp2`, `pt2`)
   - [x] `phi`
   - [x] `deltaphi(other)`
   - [x] `rotateZ(angle)`
   - [x] `transform2D(obj)` (the `obj` has items `"xx"`, `"xy"`, `"yx"`, `"yy"`)

## Implement on Spatial, to be inherited by Lorentz

   - [x] `z`
   - [x] `theta`
   - [x] `costheta`
   - [x] `cottheta`
   - [x] `eta` (`pseudorapidity`)
   - [x] `mag` (`p`)
   - [x] `mag2` (`p2`)
   - [x] `cross(other)`
   - [x] `deltaangle(other)`
   - [x] `deltaeta(other)`
   - [x] `deltaR(other)`
   - [x] `deltaR2(other)`
   - [x] `rotateX(angle)`
   - [x] `rotateY(angle)`
   - [x] `rotate_axis(axis, angle)`
   - [x] `rotate_euler(phi, theta, psi)`
   - [x] `rotate_nautical(yaw, pitch, roll)`
   - [x] `rotate_quarternion(u, i, j, k)`
   - [x] `transform3D(obj)` (the `obj` has items `"xx"`, `"xy"`, etc.)
   - [x] `is_parallel(other, tolerance)`
   - [x] `is_antiparallel(other, tolerance)`
   - [x] `is_perpendicular(other, tolerance)`

## Implement on Lorentz

   - [x] `t` (`E`, `energy`)
   - [x] `t2` (`E2`, `energy2`)
   - [x] `tau` (`m`, `mass`)
   - [x] `tau2` (`m2`, `mass2`)
   - [x] `beta`
   - [x] `gamma`
   - [x] `rapidity`
   - [x] `Et` (`transverseenergy`)
   - [x] `Et2`
   - [x] `mt` (`transversemass`)
   - [x] `mt2`
   - [x] `boostX(beta=None, gamma=None)` Either `beta` or `gamma`, but not both or neither.
   - [x] `boostY(beta=None, gamma=None)`
   - [x] `boostZ(beta=None, gamma=None)`
   - [x] `boost_p4(p4)` Use a 4-momentum vector to define the boost (numerically stable).
   - [x] `boost_beta3(beta3)` Use a 3-momentum beta vector (maximum magnitude is 1) to define the boost (less stable).
   - [x] `boost(other)` Chooses `boost_p4` or `boost_beta3` based on _type_ of argument (Vector4D vs Vector3D).
   - [x] `to_beta3()` Turns a 4-momentum into a 3-momentum beta.
   - [x] `transform4D(obj)` (the `obj` has items `"xx"`, `"xy"`, etc.)
   - [x] `is_timelike(tolerance)`
   - [x] `is_spacelike(tolerance)`
   - [x] `is_lightlike(tolerance)`

## Implement separately on all three, as the meaning depends on all coordinates

   - [x] `unit()`
   - [x] `dot(other)`
   - [x] `__abs__` (`np.absolute`) This is a synonym for `mag`.
   - [x] `__neg__` (`np.negate`) This is a synonym for `scale` by -1.
   - [x] `__pos__` This has no compute associated with it.
   - [x] `add(other)`
   - [x] `__add__` (`np.add`) This is a synonym for `add`.
   - [x] `subtract(other)`
   - [x] `__sub__` (`np.subtract`) This is a synonym for `subtract`.
   - [x] `scale(number)`
   - [x] `__mul__` (`np.multiply`) This is a synonym for `scale`.
   - [x] `__truediv__` (`np.true_divide`): This is a synonym for `scale` in which the scalar is inverted.
   - [x] `__pow__` (`np.power`) This is a synonym for `mag`, followed by raising to a power.
   - [x] `equal(other)`
   - [x] `__eq__` (`np.equal`) This is a synonym for `equal`.
   - [x] `not_equal(other)`
   - [x] `__ne__` (`np.not_equal`) This is a synonym for `not_equal`.
   - [x] `isclose(other, rtol=1e-05, atol=1e-08, equal_nan=False)` Like [np.isclose](https://numpy.org/doc/stable/reference/generated/numpy.isclose.html#:~:text=Returns%20a%20boolean%20array%20where,difference%20between%20a%20and%20b.).

In-place operations are not part of the dispatch: they replace data after the fact.

## Won't do any of the following:

   - `proj(other)`
   - `perpvectors`
   - `floor_div`
   - `mod`
   - `divmod`
   - bitwise operations

## Including these, which I don't really understand:

   - What is `TVector2::Mod()` (and `Mod2()`)?
   - What is `TVector2::Ort()`?
   - What are `ROOT::Math::DeltaR2RapidityPhi(·)` and `DeltaRapidityPhi(·)`?
   - What is `TVector3::DrEtaPhi(spatial) → scalar` (and `TLorentzVector::DrEtaPhi`)?
   - What is `TLorentzVector::DrRapidityPhi(lorentz) → scalar`?
   - What is `TVector3::EtaPhiVector() → planar` (and `TLorentzVector::EtaPhiVector`)?
   - What is `TLorentzVector::collineaerRepidity()`?
   - What is `TLorentzVector::Plus`?

### CODE REVIEW

**Comment by henryiii** [comment]
If you type "pre-commit install", then you can get the pre-commit fixes to happen when you commit instead of when you push. ;)

**Comment by jpivarski** [comment]
> If you type "pre-commit install", then you can get the pre-commit fixes to happen when you commit instead of when you push. ;)

I know, and I sometimes remember to do that.

**Comment by jpivarski** [comment]
Removing transformation objects simplifies the inheritance diagram:

**Comment by jpivarski** [comment]
If we don't have transform objects, we don't need the vector/point distinction at this level (it can be built on top, as @henryiii said), so I converted the vector/point distinction into a vector/momentum distinction.

The class diagram is even simpler now:

**Pull request merged**
